---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app
  labels:
    name: demo-app
data:

  tomcat.logging.properties: |-
{{ tpl (.Files.Get (printf "env/tomcat/tomcat-logging.properties")) . | indent 4 }}

  tomcat.catalina.properties: |-
{{ tpl (.Files.Get (printf "env/tomcat/tomcat-catalina.properties")) . | indent 4 }}

  tomcat.context.xml: |-
{{ tpl (.Files.Get (printf "env/tomcat/tomcat-context.xml")) . | indent 4 }}

  tomcat.server.xml: |-
{{ tpl (.Files.Get (printf "env/tomcat/tomcat-server.xml")) . | indent 4 }}

{{- range .Values.classPathAdditions }}
  {{ .file }}: |-
{{ $.Files.Get (printf "env/classpath/%s" .file) | indent 4 }}
{{- end }}
